### ISSUE TITLE
Rankup not working (Still not fixed)

### ISSUE THREAD

**Issue by SharkDice** [faizaand/Prison#224] opened 2017-10-07 18:24 UTC
Players cannot rankup, they're in the wrong order.

When they type /rankup, it says they don't have enough money to rank up to the max rank.

I can send any files if you need to.

Additional info...
I read the past bug reports and it seems this issue is not fixed. Please fix soon.

**Comment by DylanFPS** [comment] 2017-10-13 21:56
Potential duplicate of #221

**Closed** 2018-01-20 19:57 UTC
