### ISSUE TITLE
Prison Plugin cant be enabled

### ISSUE THREAD

**Issue by Snike02** [faizaand/Prison#213] opened 2017-05-25 12:47 UTC
I started using Prison2 a few days ago and when i got the new version 2.4.1 it started to do problems like when i write /mines it says Mines are disabled and it does that with every command.I opened the config and it says:
enable
 mines: true
 ranks: true
 autosmelt: true
 autoblock: true
 json: true
I also have PermissionsEX,Vault,WorldEdit,WorldGuard if any of this plugins are disabling it.
This is the console:
 [14:35:40] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[14:35:41] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[14:35:41] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[14:35:41] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[14:35:41] [Server thread/INFO]: [WorldGuard] Loading region data...
[14:35:42] [Server thread/INFO]: [Prison] Enabling Prison v2.4.1
[14:35:42] [Server thread/ERROR]: Error occurred while enabling Prison v2.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
at me.sirfaizdat.prison.core.Prison.bootstrap(Prison.java:103) ~[?:?]
at me.sirfaizdat.prison.core.Prison.onEnable(Prison.java:80) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~inecraft_server.jar:git-Bukkit-7019900]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) inecraft_server.jar:git-Bukkit-7019900]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) inecraft_server.jar:git-Bukkit-7019900]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) inecraft_server.jar:git-Bukkit-7019900]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) inecraft_server.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) inecraft_server.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) inecraft_server.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) inecraft_server.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) inecraft_server.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) inecraft_server.jar:git-Bukkit-7019900]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~inecraft_server.jar:git-Bukkit-7019900]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~inecraft_server.jar:git-Bukkit-7019900]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
... 13 more
[14:35:42] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:35:43] [Server thread/INFO]: Done (17.771s)! For help, type "help" or "?"
[14:35:43] [Server thread/INFO]: Starting GS4 status listener
[14:35:43] [Query Listener #1/INFO]: Query running on 0.0.0.0:57805
[14:35:43] [pool-3-thread-3/INFO]: [Vault] Checking for Updates ...
[14:35:44] [pool-3-thread-3/INFO]: [Vault] No new version available
[14:36:00] [Server thread/INFO]: Snike02[/79.126.138.158:3227] logged in with entity id 77 at ([world] -1271.6571209993147, 21.0, -1146.133600717052)
[14:36:07] [Server thread/INFO]: Snike02 issued server command: /mines
[14:36:10] [Server thread/INFO]: Snike02 issued server command: /ranks
> 
Please help me because i want to continue my work on the Prison server.

**Comment by Camouflage100** [comment] 2017-05-25 15:52
Are you using Spigot? If so what version. If not, use it.

**Comment by Snike02** [comment] 2017-05-25 16:24
Im using Bukkit not Spigot

**Comment by Camouflage100** [comment] 2017-05-25 16:28
Spigot is a requirement.

**Comment by Snike02** [comment] 2017-05-25 16:30
Okay, thanks im gonna try tomorrow because i'm not home now and tell if it worked.  :)

**Comment by DylanFPS** [comment] 2017-05-25 16:32
Possible duplicate of #210 though this provides more information

**Comment by Snike02** [comment] 2017-05-26 09:48
I put Spigot 1.8v it is still the same..
[11:46:45] [Server thread/INFO]: [Prison] Enabling Prison v2.4.1
[11:46:45] [Server thread/ERROR]: Error occurred while enabling Prison v2.4.1 (Is it up to date?)

**Comment by DylanFPS** [comment] 2017-05-26 10:09
Try turning json off in config. Note that this is unstable but it might get prison running again.

**Comment by Snike02** [comment] 2017-05-26 10:57
Nope still not working.

**Comment by DylanFPS** [comment] 2017-05-26 10:58
As I no longer maintain the project, there's little I can do for you, sorry!

**Comment by Snike02** [comment] 2017-05-27 07:36
And one more thin the version 2.3.1 works but its not saving the mines thats the reason why im not using the 2.3 and want the 2.4 to work.

**Comment by faizaand** [comment] 2017-07-03 18:03
Hello, this ticket recently resurfaced. My sincerest apologies for the delay. Are you still experiencing problems?

**Comment by MikeTheMelon** [comment] 2017-08-10 12:34
Hello faizaand! Sorry for a reply on this ticket this late! But I seem to be experiencing the same problem that the user above (Snike02) is experiencing. I have the exact same thing come up in the console. My mines and ranks are enabled but when I try running those commands in game, it says that they are disabled :/ I was just finishing up my mines last I remember. I shutdown my server for the night. Started it up today and this issue came up! I can't really think of anything that might be causing the issue. Hopefully you can reply soon!

Thanks,
Regards,
An absolute noob in server development :P

**Closed** 2018-01-20 19:57 UTC
